version: 0.1

phases:
  install:
    commands:
      - gem install bundler
      - apt-get install nodejs
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync --delete _site/ https://s3.amazonaws.com/blog.masterthe.cloud